docusaurus.config.js
src/css/custom.css

This pull request includes:
- [**fix**: changed the sidebar to be not be collapsible](https://github.com/NowYouKnowProgramming/webdev-learning-materials/commit/bff18d793659ad8ea3b0bdfe5b83c30a9195d69e)
- [fix: changed the light/dark colors to match the nykp's logo color scheme](https://github.com/NowYouKnowProgramming/webdev-learning-materials/commit/c44917b5d4e98486485b9fdd4c7fabed3634836c)

fix: changed the sidebar behavior & matched the colors

---

src/config.ts
src/pages/common/english.md
src/pages/common/hr_recruitment_resources.md
src/pages/common/job_boards.md
src/pages/common/learning_to_learn.md
src/pages/introduction.md
src/pages/principles/clean_code.md
src/pages/principles/design_patterns.md
src/pages/principles/design_ui_ux.md
src/pages/principles/testing.md
src/pages/resources/build_your_project.md
src/pages/resources/complete_project.md
src/pages/resources/content_creators.md
src/pages/resources/other_resources.md
src/pages/resources/test_your_skills.md
src/pages/technologies/css.md
src/pages/technologies/git.md
src/pages/technologies/html.md
src/pages/technologies/javascript.md
src/pages/technologies/nextjs.md
src/pages/technologies/nodejs.md
src/pages/technologies/react.md
src/pages/technologies/redux.md
src/pages/technologies/typescript.md

to improve SEO optimisation - some links have been edited to better reflect what articles are in each section
BREAKING CHANGE

Feat: add descriptions for all articles

---

src/components/Header/Search.css

Fix: Search is under header overlay

---

src/components/LandingPage/LandingPage.astro

Fix: Navbar on iOS is transparent on landing page

---

src/pages/technologies/nextjs.md

A useful video showing the rendering differences and types

Docs: add Next.js materials about rendering types

---

src/components/LandingPage/Comparison/Comparison.astro
src/components/LandingPage/Comparison/ComparisonCard.astro

to properly be indexed by google

Fix: change element types in comparison section

---

src/pages/resources/content_creators.md
src/pages/technologies/react.md

React materials

---

src/components/Header/Header.astro
src/components/LandingPage/LandingPage.astro
src/components/RightSidebar/MoreMenu.astro
src/components/RightSidebar/TableOfContents.tsx
src/styles/index.css

ReemKufiInk font is not easy to read

Readability fix

---

src/components/LeftSidebar/LeftSidebar.astro

Docs-visuals

---

astro.config.mjs
package.json
pnpm-lock.yaml
src/components/HeadCommon.astro
src/pages/resources/_exercises/css4js.md

Reverts NowYouKnowProgramming/webdev-learning-materials#148
Partytown breaks the gtag, so I'll revert the PR until I'll find the solution.

Revert "Use gtag with partytown"

---

src/components/HeadCommon.astro

Made the script easier to understand.
Also, the gtag logic is executed only in the single script tag (not separately) - this may fix the issue, but I'm not sure.

Refactor: improve the readability of the gtag injection script

---

src/pages/technologies/git.md

Docs: add Git materials #122

---

astro.config.mjs
postcss.config.cjs

Chore: add the typechecking for config files

---

src/config.ts
src/pages/common/hr_recruitment_resources.md
src/pages/common/learning_to_learn.md
src/pages/common/programmer_pov.md
src/pages/principles/design_ui_ux.md
src/pages/resources/build_your_project.md
src/pages/resources/content_creators.md
src/pages/resources/other_resources.md
src/pages/software/vim.md
src/pages/software/vscode.mdx

Docs: fix Other resources section refactor #82

---

src/components/LandingPage/LandingPageEndingCTA.astro

it was not looking good on light mode

Feat: remove glow behind LandingPageEndingCTA on light mode

---

src/components/RecommendedSections/RecommendedSections.astro
src/layouts/MainLayout.astro

Feat: add random suggested articles to the bottom of every docs page

---

src/pages/common/english.md
src/pages/common/hr_recruitment_resources.md
src/pages/common/learning_to_learn.md
src/pages/common/programmer_pov.md
src/pages/principles/design_ui_ux.md
src/pages/resources/_exercises/css4js.md
src/pages/resources/test_your_skills.mdx
src/pages/technologies/javascript.md
src/pages/technologies/react.md
src/pages/technologies/typescript.md

This pull request includes:
- added new content
- improved the structure of the Design section
- fixed the CSS 4 JS section in the "Test your skills" section
- some QoL changes for some sections

New content and QoL changes

---

src/pages/software/other_tools.md

I haven't done pull request yet, hope I didn't mess up :)

Adding CSS tool - Animista

---

src/components/LandingPage/DocsBtn.astro
src/components/LandingPage/LandingPageEndingCTA.astro
src/components/LandingPage/WelcomeSection/MainLinks.astro

Add new neon buttons to match new landing page welcome section

---

.vscode/settings.json
src/components/Footer/AvatarList.astro
src/components/Header/Header.astro
src/components/LandingPage/Comparison/Comparison.astro
src/components/LandingPage/Comparison/ComparisonCard.astro
src/components/LandingPage/DocsBtn.astro
src/components/LandingPage/Promo/FloatingIcons/FloatingIcons.tsx
src/components/LandingPage/Promo/GitStarPromoSection/GitStarPromoSection.module.css
src/components/LandingPage/Promo/GitStarPromoSection/GitStarPromoSection.tsx
src/components/LandingPage/Promo/GitStarPromoSection/Star.module.css
src/components/LandingPage/Promo/GitStarPromoSection/Star.tsx
src/components/LandingPage/Promo/ParallaxCard.module.css
src/components/LandingPage/Promo/ParallaxCard.tsx
src/components/LandingPage/Promo/ParallaxPuzzle.tsx
src/components/LandingPage/WelcomeSection/WelcomeSection.astro
src/components/LeftSidebar/LeftSidebar.astro
src/components/utility/CopyCodeToClipboard/CopyCodeToClipboard.astro
src/components/utility/HeadingLinksCopyToClipboard/HeadingLinksCopyToClipboard.astro
src/hooks/usePrefersReducedMotion.ts
src/layouts/MainLayout.astro
src/styles/index.css

- Improve styles by adding a `@media (prefers-reduced-motion)` media query in places where it is needed.
- Add a new hook named `usePrefersReducedMotion` which helps to detect if a user has enabled a setting on their device to minimize the amount of non-essential motion.
- Add a `prettier`s config file path to vscode workspace settings.

feat: respect reduced-motion preference across the website

---

src/pages/principles/design_patterns.md

Siema, ja tu zostawiam linkacz do architektury na frontendzie

feat: add frontend architecture

---

src/pages/software/vscode.mdx

Docs: add output colorizer to vscode.mdx

---

src/pages/404.astro

Feat add 404 page

---

src/pages/principles/frontend.md

feat(tools): add Fontsource (frontend)
